Use external site content for login screen
openemr/openemr pull request #4851
Opened 2022-01-24 22:55 UTC by mdsupport

PoC to insert login form in external content.

Many of the practices already have public websites. This PoC provides simple changes needed to integrate emr login with that content.

This PR inserts inline login form into open-emr.org landing page. If installed, it will show the potential although some issue that completes the login process for this change will need to be researched.

Fixes #

#### Short description of what this resolves:

#### Changes proposed in this pull request:

2022-01-24 23:00 UTC, mdsupport commented
The login button leading to the inline form is added to the top right as shown here - 

![image](https://user-images.githubusercontent.com/399047/150879194-ac3f5c84-f99f-4cc6-9c99-7aec674b2db5.png)

2022-01-25 04:59 UTC, robertdown commented
Are you requesting this PR be accepted or just showcasing an idea?

2022-01-25 06:53 UTC, mdsupport commented
PR to get feedback about potential issues that others may have encountered - or if they used any different approach. Already had to address some CORS hurdles for open-emr.org content. But something that keeps coming up - specially for patient portal. 

Plan to close this in a day or so.

2022-01-25 11:13 UTC, adunsulag commented
One thing to bear in mind if you don't know already is with iOS devices and ITP you have to have a shared TLD if you are going to do cross origin logins that issue a cookie if you plan on staying on your original domain origin.  

If you just plan on having the login screen do a form post directly to the OpenEMR application login (which then takes them either into patient portal or the admin portal) then you're probably find, though I think we still need to use a nonce as part of the login which I didn't see in your PR (maybe I'm not following the flow completely of what you are attempting).

2022-01-25 17:31 UTC, robertdown requested changes

2022-01-25 17:31 UTC, robertdown commented on interface/login/login.php
> +    $cssFix = "https://www.open-emr.org/style.min.a401b847525db22d3414c418e139dd793430539520659bb5ea12b3f144b3fc65.css";
All of this should be in its own Twig file, not in the login.php screen itself.

2022-01-25 17:31 UTC, robertdown commented on interface/login/login.php
> +<div id='inline-form-login' class='d-none'>
Can't be in this file, has to be in a Twig file

2022-01-25 17:31 UTC, robertdown commented on interface/login/login.php
> +    $('#inline-form-login > li label').addClass('text-white');
Use `document.querySelector()` instead of jQuery here.

2022-01-25 17:31 UTC, robertdown commented on interface/login/style.min.css
> +/*!* Bootstrap v4.3.1 (https://getbootstrap.com/)
Why another CSS file?

2022-01-25 17:31 UTC, robertdown commented on interface/login/login.php
> +$publicUrl = "https://www.open-emr.org/";
Needs to be configurable by the user, not hard-coded here

2022-01-25 17:33 UTC, robertdown commented
I strongly believe this should be created as a module, and not introduced into core.

2022-01-25 17:39 UTC, sjpadgett commented
I like this concept but agree with Robert, perfect for a module.
We are currently talking about setting up a custom module install pattern where module code stays with core and is turned on similar to how we do CCM/Zend modules now.

2022-01-25 18:17 UTC, adunsulag commented
@robertdown @sjpadgett I'm pretty sure this is a Proof of Concept asking for opinions on how to allow 3rd party websites to have a single click login from the external website into OpenEMR.  I'm guessing there isn't any intention in this current iteration to integrate this PR into the codebase (@mdsupport mentioned taking the PR down in a day or two).  The hard coded examples were all illustrative right @mdsupport?

Is this something that could be exposed as an open-ended API endpoint @mdsupport to grab a login form with a nonce? You could potentially embed it in an iframe with the sandbox attribute and the 'allow-top-navigation-by-user-activation' attribute.  If you expose the API this would be great as a module.

2022-01-25 21:02 UTC, mdsupport commented
Basic need here is an external website acting as gateway for emr. It becomes all the more critical for patient portal. If you have control of the external(not emr) site, best to handle an oAuth there and pass token to emr for smooth transition without login.php ever showing up.

The existing login.php is ui for initial setup and then choice of last resort for practices that do not have a web presence.

Thx all.

2022-01-25 21:02 UTC, closed without merging