Patient Record layout update 1
openemr/openemr pull request #4935
Opened 2022-02-21 06:19 UTC by mdsupport

Updates patient data display as a follow up to #4928.

1. Patient menu can provide patient record data for use by javascript.
2. The content from nav-link targets is now loaded in a common div eliminating need for each script to render menu.

2022-02-21 06:30 UTC, mdsupport commented
This change enables transfer of links from current scripts to single sub-menu.

An example included moves the patient delete button from form to Action -> Delete. Use of forms in dropdowns can also simplify workflow where staff currently is expected to 
1. fetch patient record, 
2. wait for all ajax data to load, 
3. Click edit button, 
4. Clicks the specific tab
5. Updates a field
6. Save the form.

Sample images
![image](https://user-images.githubusercontent.com/399047/154901045-453a8949-f92b-4124-9784-a1300c72b218.png)


![image](https://user-images.githubusercontent.com/399047/154900776-56c294fe-0805-444c-a20e-82115bcf25b3.png)

2022-02-22 22:44 UTC, sjpadgett commented
@robertdown How does this fit with the refactors you're doing?
I kind of like the idea of making some of the workflows, actions. Anything to speed load times etc...

2022-02-23 21:54 UTC, robertdown commented
* During load, the menu gets displayed, then, after the js runs it gets repainted in the final rendering. This is jarring and moves elements on the page which will lead to errors.
* The styling of the page sacrifices the UX of the computer user for the UX of the mobile user. While I appreciate the need for mobile compatibility, we should not trade off the computer user for the mobile user. White space and padding has value (even on mobile)
* The UI of the menu does not flow with the rest of the styling
* Inactive tooltip isn't displaying the right data in my test

`displayHorizNavBarMenu()` hasn't been moved to Twig yet, but if we are going to refactor it, we should go ahead and use a proper Twig template. Other comments in a proper review

2022-02-23 22:02 UTC, robertdown requested changes

2022-02-23 22:02 UTC, robertdown commented on interface/patient_file/summary/demographics.js
> +$('body')
Why is all of this occurring in jQuery and not just added to the HTML class?

2022-02-23 22:06 UTC, robertdown commented on interface/patient_file/summary/demographics.js
> +        disp += `<i class="fas fa-exclamation-triangle ml-1 bg-light text-warning" data-toggle="tooltip" title="${objPt.inactive_days}"></i>`;
bg-light is breaking the UI here

2022-06-10 19:48 UTC, closed without merging