weno fixes
openemr/openemr pull request #5141
Opened 2022-04-11 22:07 UTC by stephenwaite

Fixes #5140

#### Short description of what this resolves:
adds weno back to the prescription dashboard plus some minor php8 fixes

#### Changes proposed in this pull request:

2022-04-11 22:09 UTC, stephenwaite commented on interface/patient_file/summary/stats.php
> +        $display_current_medications_below = 0;
went back into the original overhaul and thinking that this makes the most sense since without it the value is always `1`

2022-04-12 00:20 UTC, robertdown requested changes
I have a PR that impacts Cards a bit. Let me submit that and see if there is a better way to go about solving this problem. I'll submit here within the hour.

2022-04-12 00:20 UTC, robertdown commented on templates/patient/card/card_base.html.twig
> +                {% block weno %}{% endblock %}
We shouldn't define special blocks in this template. This should be content and module agnostic to remain as flexible as possible.

2022-04-12 16:27 UTC, robertdown commented
Looks good

2022-04-12 16:59 UTC, merged

2022-04-12 17:03 UTC, bradymiller commented on templates/patient/card/rx.html.twig
> +            <span class="font-weight-bolder text-primary">Prescription History</span>
translate:
```
{{ "Prescription History"|xlt }}
```

2022-04-12 17:04 UTC, bradymiller commented
![2DV](https://user-images.githubusercontent.com/278968/163016128-8af177dd-a5d4-4d47-853c-117ef1c56434.gif)

2022-04-12 17:05 UTC, stephenwaite commented on templates/patient/card/rx.html.twig
> +            <span class="font-weight-bolder text-primary">Prescription History</span>
thanks @bradymiller