Fix styling and bug
openemr/openemr pull request #6434
Opened 2023-05-05 17:30 UTC by juggernautsei

Fixes #6433

#### Short description of what this resolves:
Fixes bugs in the order deletion and the requisition deletion. 
Updates styling to bootstrap x

#### Changes proposed in this pull request:

2023-05-09 17:02 UTC, adunsulag requested changes
Noted a couple minor things here.  Nothing major.

2023-05-09 17:02 UTC, adunsulag commented on library/lab.inc.php
> +function getProcedureProvider($prov_id): array
sqlFetchArray can return an array or false.  Should probably set line 101 to be $labs = sqlFetchArray($res) ?? []; or change the return type of this function.

2023-05-25 14:38 UTC, juggernautsei commented on interface/forms/requisition/new.php
> +<html lang="en">
That is correct IDE keeps doing that I will change the settings.

2023-06-03 22:50 UTC, juggernautsei commented
staying alive

2023-06-04 02:06 UTC, adunsulag commented on interface/forms/requisition/new.php
> +            exit;
Still missing the </body></html> tag on 142 and 147 and then we can bring this in.  Sorry for the delay on the turnaround here.

2023-06-04 05:12 UTC, bradymiller commented on interface/forms/requisition/new.php
> +    <title><?php echo xlt('Lab Requisition ') . $lab; ?></title>
need to escape $lab via `text($lab)`

2023-06-08 05:31 UTC, bradymiller commented on interface/forms/requisition/new.php
> +            exit;
hi @juggernautsei , looks like still need to address above. Then this should be ready.

2023-06-08 09:15 UTC, juggernautsei commented on interface/forms/requisition/new.php
> +            exit;
I am not sure why these are not being marked outdated. I have made an additional changed sugged by the IDE.

2023-06-10 10:19 UTC, juggernautsei commented
Bump

2023-06-12 05:20 UTC, bradymiller commented on interface/forms/requisition/new.php
> +    <title><?php echo xlt('Lab Requisition ') . text($lab); ?></title>
sorry, just noted this. Need to remove the trailing space in the translation constant:
```
<title><?php echo xlt('Lab Requisition') . ' ' . text($lab); ?></title>
```

2023-06-15 05:25 UTC, bradymiller commented
@juggernautsei , code looks good and bringing in. thanks for the improvements!

2023-06-15 05:26 UTC, merged