vehr remmediation
openemr/openemr pull request #6520
Opened 2023-06-06 12:23 UTC by omegasystemsgroup

#### Short description of what this resolves:
This PR includes:
1. Removing external calls to 3rd Party servers
2. Includes audit logs
3. Remove initial dummy data

2023-06-29 16:12 UTC, robertdown requested changes
I started to review this PR but there are still so many things that prevent me from considering this that I had to stop.

Please review the ListService as it will reduce a lot of your code. I don't know why you are hard coding the site_id in every script, but by doing that you ensure multi-site setups do not work. There are hard coded values all over the place, put those in a List so the end user can customize things like the colors.

It seems you are attempting to recreate and API that already exists. For instance, problems.php has a function called getMedicalProblems - that functionality already exists in the core codebase, why are you recreating it? It appears that file is acting like a Controller, ensuring you can get json_encoded data out, which is fine, but don't recreate the already existing functions.

2023-06-29 16:12 UTC, robertdown commented on interface/modules/custom_modules/oe-module-visualehr/api/active_codes.php
> +$_SESSION['site_id'] = 'default';
Don't hard code this

2023-06-29 16:12 UTC, robertdown commented on interface/modules/custom_modules/oe-module-visualehr/api/active_codes.php
> +    $colors = ["#eb5ea8", "#9f4ed3", "#99b1fc", "#7e83d0", "#fb4e4e", "#32a852", "#fb4e4e"];
These should be in a List, not hard coded

2023-06-29 16:12 UTC, robertdown commented on interface/modules/custom_modules/oe-module-visualehr/api/codetypes.php
> +$_SESSION['site_id'] = 'default';
Don't do this

2023-06-29 16:12 UTC, robertdown commented on interface/modules/custom_modules/oe-module-visualehr/api/color.php
> +    $colors = ["#eb5ea8", "#9f4ed3", "#99b1fc", "#7e83d0", "#fb4e4e", "#32a852", "#fb4e4e"];
Better to put these in a List

2023-06-29 16:12 UTC, robertdown commented on interface/modules/custom_modules/oe-module-visualehr/api/dropdown.php
> +$_SESSION['site_id'] = 'default';
No

2023-06-29 16:12 UTC, robertdown commented on interface/modules/custom_modules/oe-module-visualehr/api/dropdown.php
> +$sql = "SELECT option_id as id, list_id, title as name FROM `list_options` where list_id LIKE '%occurrence%' AND activity = 1";
Should use the ListService

2023-06-29 16:12 UTC, robertdown commented on interface/modules/custom_modules/oe-module-visualehr/api/dropdown.php
> +$sql = "SELECT option_id as id, list_id, title as name FROM `list_options` where list_id LIKE '%outcome%' AND activity = 1";
Use ListService

2023-06-29 16:12 UTC, robertdown commented on interface/modules/custom_modules/oe-module-visualehr/api/dropdown.php
> +$sql = "SELECT option_id as id, list_id, title as name FROM `list_options` where list_id LIKE '%condition-verification%' AND activity = 1";
ListService

2023-06-29 16:12 UTC, robertdown commented on interface/modules/custom_modules/oe-module-visualehr/api/dropdown.php
> +$sql = "SELECT option_id as id, list_id, title as name FROM `list_options` where list_id LIKE '%medication-usage-category%' AND activity = 1";
ListService

2023-11-13 20:06 UTC, robertdown commented
Is there anymore planned work on this PR? If not, will close.

2023-11-13 20:27 UTC, omegasystemsgroup commented
Please close. Thank you

> On Nov 13, 2023, at 8:06 PM, Robert Down RN ***@***.***> wrote:
> 
> view it on GitHub <https://github.com/openemr/openemr/pull/6520#issuecomment-1808967285>

2023-11-21 01:10 UTC, closed without merging