refactor(registration-modal): improve button colors
openemr/openemr pull request #6804
Opened 2023-08-28 19:55 UTC by raskolnikov-rodion

This is a proposal to change the colors of the buttons inside the registration modal:

![image](https://github.com/openemr/openemr/assets/22417165/3bb1c024-1f46-49e3-b1a9-7dbe5d351a1a)

This change has two purposes:
- provide better differentiation between the buttons
- grab the user's attention and highlight the action we want to encourage

This is a common UI pattern for CTAs

2023-08-28 22:52 UTC, robertdown requested changes
Good use of `btn-primary` for the button receiving the action, but leave `btn-secondary` for the cancel.

We don't have good documentation on when to use some of the other btn styles, but the general style goes "Submit buttons get primary, other actions buttons get secondary, de-emphasized action or context buttons get btn-text

2023-08-29 07:14 UTC, raskolnikov-rodion commented on templates/login/login_core.html.twig
> +                        <button type="button" class="btn btn-light nothanks">{{ "No Thanks"|xlt }}</button>
```suggestion
                        <button type="button" class="btn btn-secondary nothanks">{{ "No Thanks"|xlt }}</button>
```

2023-08-29 07:14 UTC, raskolnikov-rodion commented on templates/login/partials/html/product_registration_modal.html.twig
> +                <button type="button" class="btn btn-light nothanks">{{ "No Thanks"|xlt }}</button>
```suggestion
                <button type="button" class="btn btn-secondary nothanks">{{ "No Thanks"|xlt }}</button>
```

2023-08-29 15:43 UTC, merged

2023-08-29 15:45 UTC, robertdown commented
Thanks @raskolnikov-rodion!